[package]
name = "juk-firmware"
description = "The JUK CNC firmware running on the ESP32-S3."
version.workspace = true
authors.workspace = true
license.workspace = true

edition.workspace = true
rust-version.workspace = true

[dependencies]
esp-backtrace = { version = "0.18", features = ["defmt", "esp32s3", "panic-handler"] }
esp-bootloader-esp-idf = { version = "0.4", features = ["esp32s3"] }
esp-hal = { version = "~1.0", features = ["defmt", "esp32s3", "psram", "unstable"] }
esp-rtos = { version = "0.2", features = ["embassy", "esp32s3"] }
postcard = { version = "1.1", default-features = false, features = ["use-defmt"] }
shadow-rs = { version = "1.7", default-features = false }

bitflags = "2.11"
const_format = "0.2"
critical-section = "1.2"
defmt = "1.0"
embassy-executor = "0.9"
embassy-futures = "0.1"
embassy-sync = "0.8"
embassy-time = "0.5"
esp-alloc = "0.9"
static_cell = "2.1"

juk-cmd = { path = "../juk-cmd" }
juk-com = { path = "../juk-com" }
juk-led = { path = "../juk-led" }
juk-motion = { path = "../juk-motion" }

[dependencies.esp-println]
version = "0.16"
default-features = false
features = [
  "critical-section",
  "defmt-espflash",
  "esp32s3",
  "jtag-serial",
]

[build-dependencies]
shadow-rs = { version = "1.7", features = ["no_std"] }
