[package]
name = "juk-cmd"
description = "Command definitions and parsing for JUK2."
version.workspace = true
authors.workspace = true
license.workspace = true

edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
thiserror = { version = "2.0", default-features = false }

libm = "0.2"

defmt = { version = "1.0", features = ["alloc"], optional = true }

[features]
# Exclude code used exclusively by juk-firmware and friends
export = []
# Derive `defmt::Format` for types in this crate
defmt = ["dep:defmt"]
